import boto3
import os
import json
from datetime import date
from googleapiclient.discovery import build

# --- CONFIG ---
API_KEY = os.environ['YOUTUBE_API_KEY']
CHANNEL_ID = os.environ['CHANNEL_ID']
TABLE_NAME = os.environ['TABLE_NAME']
STATE_MACHINE_ARN = os.environ['STATE_MACHINE_ARN']

# --- CLIENTS ---
ssm = boto3.client('ssm')
sfn = boto3.client('stepfunctions')
dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table(TABLE_NAME) #type: ignore
youtube = build('youtube', 'v3', developerKey=API_KEY)

def lambda_handler(event, context):
    print("Scout waking up to check for live meetings...")
    
    # 1. Search for LIVE Council Meetings on the channel
    try:
        search_response = youtube.search().list(
            part='id,snippet',
            channelId=CHANNEL_ID,
            eventType='live',  
            type='video',
            maxResults=1
        ).execute()
    except Exception as e:
        print(f"Error querying YouTube API: {e}")
        return {'status': 'error', 'message': str(e)}

    items = search_response.get('items', [])
    
    if not items:
        print("No live council meeting found.")
        return {'status': 'no_meeting'}
        
    # We found a meeting!
    video = items[0]
    video_id = video['id']['videoId']
    title = video['snippet']['title']
    print(f"Found Live Video: {title} ({video_id})")

    # 2. IDEMPOTENCY CHECK (Prevent overlapping workflows)
    # Check if we already know about this meeting and if it's currently running.
    response = table.get_item(Key={'video_id': video_id})
    if 'Item' in response:
        if response['Item'].get('status') == 'ACTIVE':
            print(f"Meeting {video_id} is already ACTIVE. Step Function is already managing this. Going back to sleep.")
            return {'status': 'already_running', 'video_id': video_id}

    # 3. Store Video Info in SSM (For the EC2 Soldier to read when it boots)
    print("Updating SSM parameters for Soldier...")
    ssm.put_parameter(
        Name='/meeting/current_video_id',
        Value=video_id,
        Type='String',
        Overwrite=True
    )
    ssm.put_parameter(
        Name='/meeting/current_title',
        Value=title,
        Type='String',
        Overwrite=True
    )

    # 4. Create the DB Record
    print(f"Creating new DB Record for {video_id}")
    table.put_item(
        Item={
            'video_id': video_id,
            'status': 'ACTIVE',
            'start_time': str(date.today()),
            'last_checkpoint_index': 0,
            'summary': ""
        }
    )

    # 5. WAKE UP THE CONDUCTOR (Start the Step Function)
    print(f"Triggering Step Function Orchestrator for {video_id}...")
    
    # We pass the video_id and initial active state into the Step Function payload
    sfn_input = {
        "video_id": video_id,
        "meeting_active": True
    }
    
    sfn.start_execution(
        stateMachineArn=STATE_MACHINE_ARN,
        # Name is auto-generated by AWS to avoid naming collisions
        input=json.dumps(sfn_input)
    )
    
    return {'status': 'started', 'video_id': video_id, 'title': title}